name: rse_seminar
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - colorama=0.4.6
  - coverage=7.11.0
  - exceptiongroup=1.3.0
  - iniconfig=2.3.0
  - libexpat=2.7.1
  - libffi=3.5.2
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.4
  - packaging=25.0
  - pip=25.2
  - pluggy=1.6.0
  - pygments=2.19.2
  - pytest=8.4.2
  - pytest-cov=7.0.0
  - python=3.14.0
  - python_abi=3.14
  - readline=8.2
  - tk=8.6.13
  - tomli=2.3.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - zstd=1.5.7
